/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas.mesero;

import com.mycompany.javabeans_cafe.interfaces_graficas.LoginFrame;
import com.mycompany.javabeans_cafe.interfaces_graficas.mesero.cuentas.InternalVisualizadorMesas;
import com.mycompany.javabeans_cafe.modelos.Empleado;
import javax.swing.JInternalFrame;

/**
 *
 * @author matul
 */
public class MeseroPrincipalFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MeseroPrincipalFrame.class.getName());

    private static Empleado meseroLogueado;
    /**
     * Creates new form MeseroPrincipalFrame
     */
    public MeseroPrincipalFrame(Empleado mesero) {
        initComponents();
        this.meseroLogueado = mesero;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();
        jMenuPersonal = new javax.swing.JMenu();
        jMenuItemAbrirCuenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setLayout(new javax.swing.BoxLayout(jDesktopPane1, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Sesion");

        jMenuItem1.setText("Mi Cuenta");
        jMenu1.add(jMenuItem1);

        jMenuItemCerrarSesion.setText("Cerrar Sesion");
        jMenuItemCerrarSesion.addActionListener(this::jMenuItemCerrarSesionActionPerformed);
        jMenu1.add(jMenuItemCerrarSesion);

        jMenuBar1.add(jMenu1);

        jMenuPersonal.setText("Cuentas");

        jMenuItemAbrirCuenta.setText("Abrir cuenta");
        jMenuItemAbrirCuenta.addActionListener(this::jMenuItemAbrirCuentaActionPerformed);
        jMenuPersonal.add(jMenuItemAbrirCuenta);

        jMenuBar1.add(jMenuPersonal);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
        this.dispose();
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    private void jMenuItemAbrirCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirCuentaActionPerformed
        this.cerrarVentanasInternas();
        InternalVisualizadorMesas visualizadorMesas = new InternalVisualizadorMesas(meseroLogueado, jDesktopPane1);
        jDesktopPane1.add(visualizadorMesas);
        visualizadorMesas.setVisible(true);
    }//GEN-LAST:event_jMenuItemAbrirCuentaActionPerformed

    private void cerrarVentanasInternas() {
        for (JInternalFrame ventana : jDesktopPane1.getAllFrames()) {
            ventana.dispose();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAbrirCuenta;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JMenu jMenuPersonal;
    // End of variables declaration//GEN-END:variables
}
