/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas.administrador.nomina;

import com.mycompany.javabeans_cafe.enums.TipoPago;
import com.mycompany.javabeans_cafe.exceptions.NoEsFechaDePagoException;
import com.mycompany.javabeans_cafe.interfaces_graficas.modales.MensajeDialogFrame;
import com.mycompany.javabeans_cafe.modelos.PagoSalario;
import com.mycompany.javabeans_cafe.servicios.BalanceServicio;
import java.sql.SQLException;
import java.util.List;

import javax.swing.JDesktopPane;

/**
 *
 * @author matul
 */
public class InternalBalance extends javax.swing.JInternalFrame {

    private BalanceServicio balanceServicio;
    private List<PagoSalario> pagosRealizados;
    private JDesktopPane desktopPane;

    /**
     * Creates new form InternalBalance
     */
    public InternalBalance(JDesktopPane desktopPane) {
        initComponents();
        this.balanceServicio = new BalanceServicio();
        this.desktopPane = desktopPane;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelCentrado = new javax.swing.JPanel();
        jPanelFormulario = new javax.swing.JPanel();
        jPanelStockMinimo = new javax.swing.JPanel();
        jButtonPagoQuincena = new javax.swing.JButton();
        jButtonPagoFinMes = new javax.swing.JButton();
        jButtonPagoQuincenaPrueba = new javax.swing.JButton();
        jButtonPagoFinMesPrueba = new javax.swing.JButton();

        jPanelTitulo.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTitulo.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTitulo.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Pago de nomina");
        jLabelTitulo.setOpaque(true);
        jPanelTitulo.add(jLabelTitulo);

        getContentPane().add(jPanelTitulo, java.awt.BorderLayout.NORTH);

        jPanelCentrado.setBackground(new java.awt.Color(50, 52, 35));
        jPanelCentrado.setMinimumSize(new java.awt.Dimension(550, 343));
        jPanelCentrado.setPreferredSize(new java.awt.Dimension(550, 343));
        jPanelCentrado.setLayout(new java.awt.GridBagLayout());

        jPanelFormulario.setBackground(new java.awt.Color(50, 52, 35));
        jPanelFormulario.setLayout(new javax.swing.BoxLayout(jPanelFormulario, javax.swing.BoxLayout.Y_AXIS));

        jPanelStockMinimo.setBackground(new java.awt.Color(50, 52, 35));
        jPanelStockMinimo.setLayout(new java.awt.GridLayout(0, 1, 2, 5));

        jButtonPagoQuincena.setBackground(new java.awt.Color(227, 135, 88));
        jButtonPagoQuincena.setFont(new java.awt.Font("Noto Sans CJK JP Black", 0, 12)); // NOI18N
        jButtonPagoQuincena.setText("Realizar pago quincena");
        jButtonPagoQuincena.addActionListener(this::jButtonPagoQuincenaActionPerformed);
        jPanelStockMinimo.add(jButtonPagoQuincena);

        jButtonPagoFinMes.setBackground(new java.awt.Color(227, 135, 88));
        jButtonPagoFinMes.setFont(new java.awt.Font("Noto Sans CJK JP Black", 0, 12)); // NOI18N
        jButtonPagoFinMes.setText("Realizar pago fin de mes");
        jButtonPagoFinMes.addActionListener(this::jButtonPagoFinMesActionPerformed);
        jPanelStockMinimo.add(jButtonPagoFinMes);

        jButtonPagoQuincenaPrueba.setBackground(new java.awt.Color(227, 135, 88));
        jButtonPagoQuincenaPrueba.setFont(new java.awt.Font("Noto Sans CJK JP Black", 0, 12)); // NOI18N
        jButtonPagoQuincenaPrueba.setText("Realizar prueba pago quincena de mes");
        jButtonPagoQuincenaPrueba.addActionListener(this::jButtonPagoQuincenaPruebaActionPerformed);
        jPanelStockMinimo.add(jButtonPagoQuincenaPrueba);

        jButtonPagoFinMesPrueba.setBackground(new java.awt.Color(227, 135, 88));
        jButtonPagoFinMesPrueba.setFont(new java.awt.Font("Noto Sans CJK JP Black", 0, 12)); // NOI18N
        jButtonPagoFinMesPrueba.setText("Realizar prueba pago fin de mes");
        jButtonPagoFinMesPrueba.addActionListener(this::jButtonPagoFinMesPruebaActionPerformed);
        jPanelStockMinimo.add(jButtonPagoFinMesPrueba);

        jPanelFormulario.add(jPanelStockMinimo);

        jPanelCentrado.add(jPanelFormulario, new java.awt.GridBagConstraints());

        getContentPane().add(jPanelCentrado, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPagoQuincenaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonPagoQuincenaActionPerformed
        try {
            this.pagosRealizados = balanceServicio.realizarBalance(TipoPago.QUINCENA, false);
            abrirInternalResumen();
        } catch (SQLException ex) {
            String mensajeError = "Ocurrió un error al realizar el pago de la quincena. Por favor, inténtelo de nuevo más tarde.";
            mostrarMensajeError(mensajeError);
        } catch (NoEsFechaDePagoException ex) {
            String mensajeError = "No es fecha de pago de quincena. Por favor, inténtelo en la fecha correspondiente.";
            mostrarMensajeError(mensajeError);
        }
    }// GEN-LAST:event_jButtonPagoQuincenaActionPerformed

    private void jButtonPagoFinMesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonPagoFinMesActionPerformed
        try {
            this.pagosRealizados = balanceServicio.realizarBalance(TipoPago.FIN_DE_MES, false);
            abrirInternalResumen();
        } catch (SQLException ex) {
            String mensajeError = "Ocurrió un error al realizar el pago de fin de mes. Por favor, inténtelo de nuevo más tarde.";
            mostrarMensajeError(mensajeError);
        } catch (NoEsFechaDePagoException ex) {
            String mensajeError = "No es fecha de pago de fin de mes. Por favor, inténtelo en la fecha correspondiente.";
            mostrarMensajeError(mensajeError);
        }
    }// GEN-LAST:event_jButtonPagoFinMesActionPerformed

    private void jButtonPagoFinMesPruebaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonPagoFinMesPruebaActionPerformed
        try {
            this.pagosRealizados = balanceServicio.realizarBalance(TipoPago.FIN_DE_MES, true);
            abrirInternalResumen();
        } catch (SQLException ex) {
            String mensajeError = "Ocurrió un error al realizar la prueba de pago de fin de mes. Por favor, inténtelo de nuevo más tarde.";
            mostrarMensajeError(mensajeError);
        } catch (NoEsFechaDePagoException ex) {
            String mensajeError = "No es fecha de pago de fin de mes. Por favor, inténtelo en la fecha correspondiente.";
            mostrarMensajeError(mensajeError);
        }
    }// GEN-LAST:event_jButtonPagoFinMesPruebaActionPerformed

    private void jButtonPagoQuincenaPruebaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonPagoQuincenaPruebaActionPerformed
        try {
            this.pagosRealizados = balanceServicio.realizarBalance(TipoPago.QUINCENA, true);
            abrirInternalResumen();
        } catch (SQLException ex) {
            String mensajeError = "Ocurrió un error al realizar la prueba de pago de quincena. Por favor, inténtelo de nuevo más tarde.";
            mostrarMensajeError(mensajeError);
        } catch (NoEsFechaDePagoException ex) {
            String mensajeError = "No es fecha de pago de quincena. Por favor, inténtelo en la fecha correspondiente.";
            mostrarMensajeError(mensajeError);
        }
    }// GEN-LAST:event_jButtonPagoQuincenaPruebaActionPerformed

    private void mostrarMensajeError(String mensaje) {
        MensajeDialogFrame mensajeDialogFrame = new MensajeDialogFrame(null, true, mensaje, true);
        mensajeDialogFrame.setVisible(true);
    }

    private void abrirInternalResumen() {
        this.desktopPane.removeAll();
        InternalResumenPagos internalResumen = new InternalResumenPagos(pagosRealizados, balanceServicio);
        this.desktopPane.add(internalResumen);
        internalResumen.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPagoFinMes;
    private javax.swing.JButton jButtonPagoFinMesPrueba;
    private javax.swing.JButton jButtonPagoQuincena;
    private javax.swing.JButton jButtonPagoQuincenaPrueba;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelCentrado;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JPanel jPanelStockMinimo;
    private javax.swing.JPanel jPanelTitulo;
    // End of variables declaration//GEN-END:variables
}
