/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas.administrador.nomina;

import java.util.List;

import javax.swing.table.DefaultTableModel;

import com.mycompany.javabeans_cafe.modelos.PagoSalario;
import com.mycompany.javabeans_cafe.servicios.BalanceServicio;

/**
 *
 * @author matul
 */
public class InternalResumenPagos extends javax.swing.JInternalFrame {

    private List<PagoSalario> pagosRealizados;
    private BalanceServicio balanceServicio;

    /**
     * Creates new form InternalResumenPagos
     */
    public InternalResumenPagos(List<PagoSalario> pagosRealizados, BalanceServicio balanceServicio) {
        this.pagosRealizados = pagosRealizados;
        this.balanceServicio = balanceServicio;
        initComponents();
        mostrarTotalPagado();
        colocarPagosEnTabla();

    }

    private void colocarPagosEnTabla() {

        String[] columnas = {
                "Codigo nomina",
                "Codigo empleado",
                "DPI empleado",
                "Fecha y hora de emisión",
                "Tipo de pago",
                "Monto pago",
                "Estado pago"
        };

        DefaultTableModel modeloInsumos = crearModelo(columnas);

        if (pagosRealizados != null) {
            for (PagoSalario pago : pagosRealizados) {
                modeloInsumos.addRow(convertirPagoAFila(pago));
            }
        }

        jTableInsumos.setModel(modeloInsumos);
    }

    private DefaultTableModel crearModelo(String[] columnas) {
        return new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
    }

    private Object[] convertirPagoAFila(PagoSalario pago) {
        return new Object[] {
                pago.getCodigoNomina(),
                pago.getCodigoEmpleado(),
                pago.getDpiEmpleado(),
                pago.getFechaHoraEmision(),
                pago.getTipoPago(),
                pago.getMontoPago(),
                pago.getEstado()
        };
    }

    private void mostrarTotalPagado() {
        if (balanceServicio != null) {
            jLabelTotalPagado.setText("Total: Q. " + balanceServicio.getTotalPagado());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelTituloLista = new javax.swing.JLabel();
        jPanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInsumos = new javax.swing.JTable();
        jPanelTotalPagado = new javax.swing.JPanel();
        jLabelTotalPagado = new javax.swing.JLabel();

        jPanel.setBackground(new java.awt.Color(50, 52, 35));
        jPanel.setLayout(new java.awt.BorderLayout());

        jPanelTitulo.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTituloLista.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTituloLista.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTituloLista.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTituloLista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloLista.setText("Pagos realizados");
        jLabelTituloLista.setOpaque(true);
        jPanelTitulo.add(jLabelTituloLista);

        jPanel.add(jPanelTitulo, java.awt.BorderLayout.NORTH);

        jPanelTabla.setBackground(new java.awt.Color(50, 52, 35));
        jPanelTabla.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 20, 20));
        jPanelTabla.setLayout(new java.awt.BorderLayout());

        jTableInsumos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(jTableInsumos);

        jPanelTabla.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel.add(jPanelTabla, java.awt.BorderLayout.CENTER);

        jPanelTotalPagado.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTotalPagado.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTotalPagado.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTotalPagado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalPagado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTotalPagado.setText("Total: Q. 00.00");
        jLabelTotalPagado.setOpaque(true);
        jPanelTotalPagado.add(jLabelTotalPagado);

        jPanel.add(jPanelTotalPagado, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTituloLista;
    private javax.swing.JLabel jLabelTotalPagado;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JPanel jPanelTotalPagado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableInsumos;
    // End of variables declaration//GEN-END:variables
}
