/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas.administrador.internals.gestion_menu;

import java.sql.SQLException;
import java.util.List;

import com.mycompany.javabeans_cafe.daos.ProductoMenuDAO;
import com.mycompany.javabeans_cafe.enums.CategoriaProducto;
import com.mycompany.javabeans_cafe.interfaces_graficas.modales.MensajeDialogFrame;
import com.mycompany.javabeans_cafe.modelos.ProductoMenu;

/**
 *
 * @author matul
 */
public class InternalVisulizarMenu extends javax.swing.JInternalFrame {

    private ProductoMenuDAO productoMenuDAO;
    private List<ProductoMenu> bebidasCalientes;
    private List<ProductoMenu> bebidasFrias;
    private List<ProductoMenu> postres;
    private List<ProductoMenu> comidas;
    /**
     * Creates new form InternalVisulizarMenu
     */
    public InternalVisulizarMenu() {
        initComponents();
        this.productoMenuDAO = new ProductoMenuDAO();
        cargarProductos();
        cargarProductosEnPaneles();
    }


    private void cargarProductos(){
        cargarBebidasCalientes();
        cargarBebidasFrias();
        cargarPostres();
        cargarComidas();
    }

    private void cargarProductosEnPaneles(){

        cargarBebidasCalientesEnPanel();
        cargarBebidasFriasEnPanel();
        cargarPostresEnPanel();
        cargarComidasEnPanel();
    }

    private void cargarBebidasCalientesEnPanel(){
        for (ProductoMenu producto : bebidasCalientes) {
            PanelProductoMenu panelProducto = new PanelProductoMenu(producto);
            jPanelParaBebidasCalientes.add(panelProducto);
        }
    }

    private void cargarBebidasFriasEnPanel(){
        for (ProductoMenu producto : bebidasFrias) {
            PanelProductoMenu panelProducto = new PanelProductoMenu(producto);
            jPanelParaBebidasFrias.add(panelProducto);
        }
    }

    private void cargarPostresEnPanel(){
        for (ProductoMenu producto : postres) {
            PanelProductoMenu panelProducto = new PanelProductoMenu(producto);
            jPanelParaPostres.add(panelProducto);
        }
    }

    private void cargarComidasEnPanel(){
        for (ProductoMenu producto : comidas) {
            PanelProductoMenu panelProducto = new PanelProductoMenu(producto);
            jPanelParaComidas.add(panelProducto);
        }
    }
    
    private void cargarBebidasCalientes(){
        try {
            this.bebidasCalientes = productoMenuDAO.obtenerProductosPorCategoria(CategoriaProducto.BEBIDA_CALIENTE);
        } catch (SQLException e) {
            String mensajeError = "Error al cargar las bebidas calientes: " + e.getMessage();
            mostrarMensajeError(mensajeError);
        }

    }

    private void cargarBebidasFrias(){
        try {
            this.bebidasFrias = productoMenuDAO.obtenerProductosPorCategoria(CategoriaProducto.BEBIDA_FRIA);
        } catch (SQLException e) {
            String mensajeError = "Error al cargar las bebidas frías: " + e.getMessage();
            mostrarMensajeError(mensajeError);
        }

    }

    private void cargarPostres(){
        
        try {
            this.postres = productoMenuDAO.obtenerProductosPorCategoria(CategoriaProducto.POSTRE);
        } catch (SQLException e) {
            String mensajeError = "Error al cargar los postres: " + e.getMessage();
            mostrarMensajeError(mensajeError);
        }

    }

    private void cargarComidas(){

        try {
            this.comidas = productoMenuDAO.obtenerProductosPorCategoria(CategoriaProducto.COMIDA);
        } catch (SQLException e) {
            String mensajeError = "Error al cargar las comidas: " + e.getMessage();
            mostrarMensajeError(mensajeError);
        }

    }

    private void mostrarMensajeError(String mensaje) {
        MensajeDialogFrame mensajeDialog = new MensajeDialogFrame(null, true, mensaje, true);
        mensajeDialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelVisualizador = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelParaBebidasCalientes = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanelParaBebidasFrias = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelTitulo3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanelParaPostres = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabelTitulo4 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanelParaComidas = new javax.swing.JPanel();

        jPanel.setBackground(new java.awt.Color(50, 52, 35));
        jPanel.setLayout(new java.awt.BorderLayout());

        jPanelTitulo.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTitulo.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTitulo.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Menu");
        jLabelTitulo.setOpaque(true);
        jPanelTitulo.add(jLabelTitulo);

        jPanel.add(jPanelTitulo, java.awt.BorderLayout.NORTH);

        jPanelVisualizador.setBackground(new java.awt.Color(50, 52, 35));
        jPanelVisualizador.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 20, 20));
        jPanelVisualizador.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabelTitulo1.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTitulo1.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo1.setText("Bebidas Calientes");
        jLabelTitulo1.setOpaque(true);
        jPanel1.add(jLabelTitulo1, java.awt.BorderLayout.NORTH);

        jPanelParaBebidasCalientes.setLayout(new java.awt.GridLayout(0, 6, 10, 10));
        jScrollPane1.setViewportView(jPanelParaBebidasCalientes);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelVisualizador.add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabelTitulo2.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTitulo2.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTitulo2.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo2.setText("Bebidas Frias");
        jLabelTitulo2.setOpaque(true);
        jPanel2.add(jLabelTitulo2, java.awt.BorderLayout.NORTH);

        jPanelParaBebidasFrias.setLayout(new java.awt.GridLayout(0, 6, 10, 10));
        jScrollPane5.setViewportView(jPanelParaBebidasFrias);

        jPanel2.add(jScrollPane5, java.awt.BorderLayout.CENTER);

        jPanelVisualizador.add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabelTitulo3.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTitulo3.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTitulo3.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo3.setText("Postres");
        jLabelTitulo3.setOpaque(true);
        jPanel3.add(jLabelTitulo3, java.awt.BorderLayout.NORTH);

        jPanelParaPostres.setLayout(new java.awt.GridLayout(0, 6, 10, 10));
        jScrollPane6.setViewportView(jPanelParaPostres);

        jPanel3.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        jPanelVisualizador.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabelTitulo4.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTitulo4.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTitulo4.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo4.setText("Comidas");
        jLabelTitulo4.setOpaque(true);
        jPanel4.add(jLabelTitulo4, java.awt.BorderLayout.NORTH);

        jPanelParaComidas.setLayout(new java.awt.GridLayout(0, 6, 10, 10));
        jScrollPane7.setViewportView(jPanelParaComidas);

        jPanel4.add(jScrollPane7, java.awt.BorderLayout.CENTER);

        jPanelVisualizador.add(jPanel4);

        jPanel.add(jPanelVisualizador, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JLabel jLabelTitulo3;
    private javax.swing.JLabel jLabelTitulo4;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelParaBebidasCalientes;
    private javax.swing.JPanel jPanelParaBebidasFrias;
    private javax.swing.JPanel jPanelParaComidas;
    private javax.swing.JPanel jPanelParaPostres;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JPanel jPanelVisualizador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables
}
