/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas.administrador.internals.gestion_menu;

import javax.swing.ImageIcon;
import java.awt.Image;

import com.mycompany.javabeans_cafe.modelos.ProductoMenu;

/**
 *
 * @author matul
 */
public class PanelProductoMenu extends javax.swing.JPanel {


    private ProductoMenu producto;
    /**
     * Creates new form PanelProductoMenu
     */
    public PanelProductoMenu(ProductoMenu producto) {
        initComponents();
        this.producto = producto;
        actualizarInformacionProducto();
    }

    private void actualizarInformacionProducto() {
        jLabelTitulo.setText(producto.getNombreProducto());
        jLabelPrecio.setText("Q. " + producto.getPrecioVenta().toString());
        jLabelImagen.setSize(70, 70); 
        mostrarImagen(producto.getImagen());
    }

    private void mostrarImagen(byte[] imagen) {
        if (imagen == null || imagen.length == 0) {
            jLabelImagen.setIcon(null);
            jLabelImagen.setText("Sin imagen");
            return;
        }

        ImageIcon imagenOriginal = new ImageIcon(imagen);

        Image imagenEscalada = imagenOriginal.getImage()
                .getScaledInstance(
                        100,
                        100,
                        Image.SCALE_SMOOTH);

        jLabelImagen.setText("");
        jLabelImagen.setIcon(new ImageIcon(imagenEscalada));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelImagen = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabelTitulo.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTitulo.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 12)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Nombre producto");
        jLabelTitulo.setOpaque(true);
        add(jLabelTitulo, java.awt.BorderLayout.NORTH);

        jLabelImagen.setBackground(new java.awt.Color(50, 52, 35));
        jLabelImagen.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelImagen.setForeground(new java.awt.Color(227, 135, 88));
        jLabelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagen.setText("Imagen");
        jLabelImagen.setOpaque(true);
        add(jLabelImagen, java.awt.BorderLayout.CENTER);

        jLabelPrecio.setBackground(new java.awt.Color(50, 52, 35));
        jLabelPrecio.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 14)); // NOI18N
        jLabelPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPrecio.setText("Q. 10.00");
        jLabelPrecio.setOpaque(true);
        add(jLabelPrecio, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
