/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas.mesero.cuentas;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JDesktopPane;

import com.mycompany.javabeans_cafe.daos.MesaDAO;
import com.mycompany.javabeans_cafe.interfaces_graficas.modales.MensajeDialogFrame;
import com.mycompany.javabeans_cafe.modelos.Empleado;
import com.mycompany.javabeans_cafe.modelos.Mesa;

/**
 *
 * @author matul
 */
public class InternalVisualizadorMesas extends javax.swing.JInternalFrame {

    private List<Mesa> mesasCargadas = new ArrayList<>();
    private Empleado empleado;
    private JDesktopPane jDesktopPane;

    /**
     * Creates new form InternalVisualizadorMesas
     */
    public InternalVisualizadorMesas(Empleado empleado, JDesktopPane jDesktopPane) {
        initComponents();
        this.empleado = empleado;
        this.jDesktopPane = jDesktopPane;
        cargarMesas();
        definirGridPanelMesas();
        agregarPanelMesa();
    }

    private void cargarMesas() {
        mesasCargadas.clear();

        MesaDAO mesaDAO = new MesaDAO();

        try {
            List<Mesa> mesas = mesaDAO.obtenerTodos();
            mesasCargadas.addAll(mesas);
        } catch (SQLException e) {
            String mensajeError = "Error al cargar mesas: " + e.getMessage();
            MensajeDialogFrame frameError = new MensajeDialogFrame(null, true, mensajeError, true);
            frameError.setVisible(true);
        }
    }

    private void definirGridPanelMesas() {
        jPanelParaMesas.setLayout(new java.awt.GridLayout(0, 4, 15, 15));
    }

    private void agregarPanelMesa() {
        jPanelParaMesas.removeAll();

        for (Mesa mesa : mesasCargadas) {
            PanelMesaCuenta panelMesa = new PanelMesaCuenta(mesa, jDesktopPane, empleado);
            jPanelParaMesas.add(panelMesa);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelVisualizador = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelParaMesas = new javax.swing.JPanel();

        jPanel.setBackground(new java.awt.Color(50, 52, 35));
        jPanel.setLayout(new java.awt.BorderLayout());

        jPanelTitulo.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTitulo.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTitulo.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Mesas");
        jLabelTitulo.setOpaque(true);
        jPanelTitulo.add(jLabelTitulo);

        jPanel.add(jPanelTitulo, java.awt.BorderLayout.NORTH);

        jPanelVisualizador.setBackground(new java.awt.Color(50, 52, 35));
        jPanelVisualizador.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 20, 20));
        jPanelVisualizador.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanelParaMesasLayout = new javax.swing.GroupLayout(jPanelParaMesas);
        jPanelParaMesas.setLayout(jPanelParaMesasLayout);
        jPanelParaMesasLayout.setHorizontalGroup(
                jPanelParaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 644, Short.MAX_VALUE));
        jPanelParaMesasLayout.setVerticalGroup(
                jPanelParaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 260, Short.MAX_VALUE));

        jScrollPane1.setViewportView(jPanelParaMesas);

        jPanelVisualizador.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel.add(jPanelVisualizador, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanelParaMesas;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JPanel jPanelVisualizador;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
