/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas.mesero.cuentas;

import java.sql.SQLException;
import java.util.List;

import javax.swing.JDesktopPane;

import com.mycompany.javabeans_cafe.daos.PedidoDAO;
import com.mycompany.javabeans_cafe.interfaces_graficas.modales.MensajeDialogFrame;
import com.mycompany.javabeans_cafe.modelos.Pedido;
import java.util.ArrayList;

/**
 *
 * @author matul
 */
public class InternalVisulizadorPedidos extends javax.swing.JInternalFrame {

    private List<Pedido> pedidosCargados;
    private int codigoEmpleado;
    private JDesktopPane jDesktopPane;

    /**
     * Creates new form InternalVisulizadorPedidos
     */
    public InternalVisulizadorPedidos(int codigoEmpleado, JDesktopPane jDesktopPane) {
        this.codigoEmpleado = codigoEmpleado;
        this.jDesktopPane = jDesktopPane;
        this.codigoEmpleado = codigoEmpleado;
        this.jDesktopPane = jDesktopPane;
        initComponents();
        cargarPedidos();
    }

    private void cargarPedidos() {
        jComboBoxPedidos.removeAllItems();
        this.pedidosCargados = new ArrayList<>();
        pedidosCargados.clear();
        

        PedidoDAO pedidoDAO = new PedidoDAO();

        try {
            List<Pedido> pedidos = pedidoDAO.obtenerAbiertosPorEmpleado(codigoEmpleado);
            pedidosCargados.addAll(pedidos);
            for (Pedido pedido : pedidos) {
                jComboBoxPedidos.addItem("Pedido " + pedido.getCodigoPedido() + " - Mesa: " + pedido.getNumeroMesa());
            }
        } catch (SQLException e) {
            String mensajeError = "Error al cargar pedidos: " + e.getMessage();
            MensajeDialogFrame frameError = new MensajeDialogFrame(null, true, mensajeError, true);
            frameError.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelCentrado = new javax.swing.JPanel();
        jPanelFormulario = new javax.swing.JPanel();
        jPanelSeleccionCuenta = new javax.swing.JPanel();
        jLabelCuentaSeleccion = new javax.swing.JLabel();
        jComboBoxPedidos = new javax.swing.JComboBox<>();
        jPanelBoton = new javax.swing.JPanel();
        jButtonIrPedido = new javax.swing.JButton();

        jPanelTitulo.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTitulo.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTitulo.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Seleccion de Cuentas Abiertas");
        jLabelTitulo.setOpaque(true);
        jPanelTitulo.add(jLabelTitulo);

        getContentPane().add(jPanelTitulo, java.awt.BorderLayout.NORTH);

        jPanelCentrado.setBackground(new java.awt.Color(50, 52, 35));
        jPanelCentrado.setMinimumSize(new java.awt.Dimension(550, 343));
        jPanelCentrado.setPreferredSize(new java.awt.Dimension(550, 343));
        jPanelCentrado.setLayout(new java.awt.GridBagLayout());

        jPanelFormulario.setBackground(new java.awt.Color(50, 52, 35));
        jPanelFormulario.setLayout(new javax.swing.BoxLayout(jPanelFormulario, javax.swing.BoxLayout.Y_AXIS));

        jPanelSeleccionCuenta.setBackground(new java.awt.Color(50, 52, 35));
        jPanelSeleccionCuenta.setLayout(new java.awt.GridLayout(0, 1, 2, 5));

        jLabelCuentaSeleccion.setBackground(new java.awt.Color(50, 52, 35));
        jLabelCuentaSeleccion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCuentaSeleccion.setText("Seleccione una cuenta");
        jLabelCuentaSeleccion.setOpaque(true);
        jPanelSeleccionCuenta.add(jLabelCuentaSeleccion);

        jComboBoxPedidos.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPedidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 135, 88)));
        jPanelSeleccionCuenta.add(jComboBoxPedidos);

        jPanelFormulario.add(jPanelSeleccionCuenta);

        jPanelCentrado.add(jPanelFormulario, new java.awt.GridBagConstraints());

        getContentPane().add(jPanelCentrado, java.awt.BorderLayout.CENTER);

        jPanelBoton.setBackground(new java.awt.Color(50, 52, 35));

        jButtonIrPedido.setBackground(new java.awt.Color(227, 135, 88));
        jButtonIrPedido.setFont(new java.awt.Font("Noto Sans CJK JP Black", 0, 12)); // NOI18N
        jButtonIrPedido.setText("Ir al Pedido");
        jButtonIrPedido.addActionListener(this::jButtonIrPedidoActionPerformed);
        jPanelBoton.add(jButtonIrPedido);

        getContentPane().add(jPanelBoton, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIrPedidoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonIrPedidoActionPerformed
        Pedido pedidoSeleccionado = pedidosCargados.get(jComboBoxPedidos.getSelectedIndex());
        jDesktopPane.removeAll();
        InternalCuentaAbierta internalPedido = new InternalCuentaAbierta(pedidoSeleccionado.getNumeroMesa());
        jDesktopPane.add(internalPedido);
        internalPedido.setVisible(true);
    }// GEN-LAST:event_jButtonIrPedidoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIrPedido;
    private javax.swing.JComboBox<String> jComboBoxPedidos;
    private javax.swing.JLabel jLabelCuentaSeleccion;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelBoton;
    private javax.swing.JPanel jPanelCentrado;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JPanel jPanelSeleccionCuenta;
    private javax.swing.JPanel jPanelTitulo;
    // End of variables declaration//GEN-END:variables
}
