/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas.mesero.cuentas;

import com.mycompany.javabeans_cafe.modelos.ProductoPedidoConNombre;

/**
 *
 * @author matul
 */
public class PanelProductoSinConfirmar extends javax.swing.JPanel {

    private ProductoPedidoConNombre producto;
    private InternalCuentaAbierta internal;

    /**
     * Creates new form PanelProductoSinConfirmar
     */
    public PanelProductoSinConfirmar(ProductoPedidoConNombre producto, InternalCuentaAbierta internal) {
        initComponents();
        this.internal = internal;
        this.producto = producto;
        actualizarPanel(producto);
        
    }

    private void actualizarPanel(ProductoPedidoConNombre producto) {
        jLabelCantidad.setText(String.valueOf(producto.getProductoPedido().getCantidad()));
        JLabelNombreProducto.setText(producto.getNombreProducto());
        jLabelSubtotal.setText("Q. " + producto.getProductoPedido().getSubtotal().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCantidad = new javax.swing.JLabel();
        JLabelNombreProducto = new javax.swing.JLabel();
        jLabelSubtotal = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabelCantidad.setBackground(new java.awt.Color(50, 52, 35));
        jLabelCantidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCantidad.setText("Cantidad");
        jLabelCantidad.setOpaque(true);
        jPanel1.add(jLabelCantidad);

        JLabelNombreProducto.setBackground(new java.awt.Color(50, 52, 35));
        JLabelNombreProducto.setForeground(new java.awt.Color(255, 255, 255));
        JLabelNombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelNombreProducto.setText("Nombre producto");
        JLabelNombreProducto.setOpaque(true);
        jPanel1.add(JLabelNombreProducto);

        jLabelSubtotal.setBackground(new java.awt.Color(50, 52, 35));
        jLabelSubtotal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSubtotal.setText("Subtotal");
        jLabelSubtotal.setOpaque(true);
        jPanel1.add(jLabelSubtotal);

        jButtonEditar.setBackground(new java.awt.Color(50, 52, 35));
        jButtonEditar.setFont(new java.awt.Font("Noto Sans CJK JP Black", 0, 12)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setText("Quitar");
        jButtonEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 135, 88)));
        jButtonEditar.addActionListener(this::jButtonEditarActionPerformed);
        jPanel1.add(jButtonEditar);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonEditarActionPerformed
        internal.eliminarProductoSinConfirmar(producto);
    }// GEN-LAST:event_jButtonEditarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelNombreProducto;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelSubtotal;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
