/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas.administrador;

import com.mycompany.javabeans_cafe.interfaces_graficas.LoginFrame;
import com.mycompany.javabeans_cafe.interfaces_graficas.administrador.internals.gestion_empleados.InternalDesactivarEmpleado;
import com.mycompany.javabeans_cafe.interfaces_graficas.administrador.internals.gestion_empleados.InternalEditorEmpleado;
import com.mycompany.javabeans_cafe.interfaces_graficas.administrador.internals.gestion_empleados.InternalListaEmpleados;
import com.mycompany.javabeans_cafe.interfaces_graficas.administrador.internals.gestion_empleados.InternalRegistroEmpleado;
import javax.swing.JInternalFrame;

/**
 *
 * @author matul
 */
public class AdminPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(AdminPrincipal.class.getName());

    /**
     * Creates new form AdminPrincipal
     */
    public AdminPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemCerrarSesion = new javax.swing.JMenuItem();
        jMenuPersonal = new javax.swing.JMenu();
        jMenuItemRegistrarEmpleado = new javax.swing.JMenuItem();
        jMenuIemEditarEmpleado = new javax.swing.JMenuItem();
        jMenuItemActivarDesactivar = new javax.swing.JMenuItem();
        jMenuItemListaEmpleados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jDesktopPane1.setLayout(new javax.swing.BoxLayout(jDesktopPane1, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jDesktopPane1);

        jMenu1.setText("Sesion");

        jMenuItem1.setText("Mi Cuenta");
        jMenu1.add(jMenuItem1);

        jMenuItemCerrarSesion.setText("Cerrar Sesion");
        jMenuItemCerrarSesion.addActionListener(this::jMenuItemCerrarSesionActionPerformed);
        jMenu1.add(jMenuItemCerrarSesion);

        jMenuBar1.add(jMenu1);

        jMenuPersonal.setText("Personal");

        jMenuItemRegistrarEmpleado.setText("Registrar Empleado");
        jMenuItemRegistrarEmpleado.addActionListener(this::jMenuItemRegistrarEmpleadoActionPerformed);
        jMenuPersonal.add(jMenuItemRegistrarEmpleado);

        jMenuIemEditarEmpleado.setText("Editar Empleado");
        jMenuIemEditarEmpleado.addActionListener(this::jMenuIemEditarEmpleadoActionPerformed);
        jMenuPersonal.add(jMenuIemEditarEmpleado);

        jMenuItemActivarDesactivar.setText("Activar / Desactivar");
        jMenuItemActivarDesactivar.addActionListener(this::jMenuItemActivarDesactivarActionPerformed);
        jMenuPersonal.add(jMenuItemActivarDesactivar);

        jMenuItemListaEmpleados.setText("Lista de Empleados");
        jMenuItemListaEmpleados.addActionListener(this::jMenuItemListaEmpleadosActionPerformed);
        jMenuPersonal.add(jMenuItemListaEmpleados);

        jMenuBar1.add(jMenuPersonal);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuIemEditarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIemEditarEmpleadoActionPerformed
        this.cerrarVentanasInternas();
        InternalEditorEmpleado editorEmpleado = new InternalEditorEmpleado();
        jDesktopPane1.add(editorEmpleado);
       editorEmpleado.setVisible(true);
    }//GEN-LAST:event_jMenuIemEditarEmpleadoActionPerformed

    private void jMenuItemActivarDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActivarDesactivarActionPerformed
        this.cerrarVentanasInternas();
        InternalDesactivarEmpleado activarDesactivar = new InternalDesactivarEmpleado();
        jDesktopPane1.add(activarDesactivar);
        activarDesactivar.setVisible(true);
    }//GEN-LAST:event_jMenuItemActivarDesactivarActionPerformed

    private void jMenuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesionActionPerformed
        this.dispose();
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.setVisible(true);
    }//GEN-LAST:event_jMenuItemCerrarSesionActionPerformed

    private void jMenuItemListaEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListaEmpleadosActionPerformed
         this.cerrarVentanasInternas();
        InternalListaEmpleados listaEmpleados = new InternalListaEmpleados();
        jDesktopPane1.add(listaEmpleados);
        listaEmpleados.setVisible(true);
    }//GEN-LAST:event_jMenuItemListaEmpleadosActionPerformed

    private void jMenuItemRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItemRegistrarEmpleadoActionPerformed
        this.cerrarVentanasInternas();
        InternalRegistroEmpleado registrarEmpleado = new InternalRegistroEmpleado();
        jDesktopPane1.add(registrarEmpleado);
        registrarEmpleado.setVisible(true);
    }// GEN-LAST:event_jMenuItemRegistrarEmpleadoActionPerformed

    private void cerrarVentanasInternas() {
        for (JInternalFrame ventana : jDesktopPane1.getAllFrames()) {
            ventana.dispose();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuIemEditarEmpleado;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemActivarDesactivar;
    private javax.swing.JMenuItem jMenuItemCerrarSesion;
    private javax.swing.JMenuItem jMenuItemListaEmpleados;
    private javax.swing.JMenuItem jMenuItemRegistrarEmpleado;
    private javax.swing.JMenu jMenuPersonal;
    // End of variables declaration//GEN-END:variables
}
