/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas.administrador.internals.gestionn_insumos;

import java.sql.SQLException;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import com.mycompany.javabeans_cafe.daos.InsumoDAO;
import com.mycompany.javabeans_cafe.interfaces_graficas.modales.MensajeDialogFrame;
import com.mycompany.javabeans_cafe.modelos.Insumo;

/**
 *
 * @author matul
 */
public class InternalListaInsumosBajoStock extends javax.swing.JInternalFrame {

    private InsumoDAO insumoDAO;
    private List<Insumo> insumosBajosDeStock;

    /**
     * Creates new form InternalListaInsumosBajoStock
     */
    public InternalListaInsumosBajoStock() {
        initComponents();
        this.insumoDAO = new InsumoDAO();

        boolean cargaExitosa = cargarInsumos();
        colocarInsumosEnTabla();

        if (cargaExitosa && insumosBajosDeStock.isEmpty()) {
            String mensaje = "No hay insumos con bajo stock.";
            MensajeDialogFrame mensajeDialogFrame = new MensajeDialogFrame(null, true, mensaje);
            mensajeDialogFrame.setVisible(true);
        }
    }

    private boolean cargarInsumos() {
        try {
            this.insumosBajosDeStock = insumoDAO.obtenerConStockBajo();
            return true;
        } catch (SQLException e) {
            String mensajeError = "Error al cargar los insumos: " + e.getMessage();
            MensajeDialogFrame mensajeDialogFrame = new MensajeDialogFrame(null, true, mensajeError, true);
            mensajeDialogFrame.setVisible(true);
            return false;
        }
    }

    private void colocarInsumosEnTabla() {

        String[] columnas = {
                "Código Insumo",
                "Nombre Insumo",
                "Stock Actual",
                "Stock Mínimo",
                "Costo Insumo"
        };

        DefaultTableModel modeloInsumos = crearModelo(columnas);

        if (insumosBajosDeStock != null) {
            for (Insumo insumo : insumosBajosDeStock) {
                modeloInsumos.addRow(convertirInsumoAFila(insumo));
            }
        }

        jTableInsumos.setModel(modeloInsumos);
    }

    private DefaultTableModel crearModelo(String[] columnas) {
        return new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
    }

    private Object[] convertirInsumoAFila(Insumo insumo) {
        return new Object[] {
                insumo.getCodigoInsumo(),
                insumo.getNombreInsumo(),
                insumo.getStockActual(),
                insumo.getStockMinimo(),
                insumo.getCostoInsumo()
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelTituloLista = new javax.swing.JLabel();
        jPanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInsumos = new javax.swing.JTable();

        jPanel.setBackground(new java.awt.Color(50, 52, 35));
        jPanel.setLayout(new java.awt.BorderLayout());

        jPanelTitulo.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTituloLista.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTituloLista.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTituloLista.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTituloLista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloLista.setText("Lista de insumos con bajo stock");
        jLabelTituloLista.setOpaque(true);
        jPanelTitulo.add(jLabelTituloLista);

        jPanel.add(jPanelTitulo, java.awt.BorderLayout.NORTH);

        jPanelTabla.setBackground(new java.awt.Color(50, 52, 35));
        jPanelTabla.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 20, 20));
        jPanelTabla.setLayout(new java.awt.BorderLayout());

        jTableInsumos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(jTableInsumos);

        jPanelTabla.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel.add(jPanelTabla, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTituloLista;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableInsumos;
    // End of variables declaration//GEN-END:variables
}
