/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas.modales;

/**
 *
 * @author matul
 */
public class MensajeDialogFrame extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(MensajeDialogFrame.class.getName());

    private boolean isError;

    /**
     * Creates new form MensajeDialogFrame
     */
    public MensajeDialogFrame(java.awt.Frame parent, boolean modal, String mensaje, boolean isError) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.isError = isError;

        mostrarMensaje(isError, mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jPanelBoton = new javax.swing.JPanel();
        jButtonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelTitulo.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTitulo.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTitulo.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Titulo");
        jLabelTitulo.setOpaque(true);
        jPanelTitulo.add(jLabelTitulo);

        getContentPane().add(jPanelTitulo, java.awt.BorderLayout.NORTH);

        jLabelDescripcion.setBackground(new java.awt.Color(50, 52, 35));
        jLabelDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDescripcion.setText("Descripcion");
        jLabelDescripcion.setOpaque(true);
        getContentPane().add(jLabelDescripcion, java.awt.BorderLayout.CENTER);

        jPanelBoton.setBackground(new java.awt.Color(50, 52, 35));

        jButtonAceptar.setBackground(new java.awt.Color(227, 135, 88));
        jButtonAceptar.setFont(new java.awt.Font("Noto Sans CJK JP Black", 0, 12)); // NOI18N
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(this::jButtonAceptarActionPerformed);
        jPanelBoton.add(jButtonAceptar);

        getContentPane().add(jPanelBoton, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarMensaje(boolean isError, String descripcion) {
        jLabelTitulo.setText(isError ? "Error" : "Exito");
        jLabelDescripcion.setText(
        "<html><div style='width:220px; text-align:center;'>"
        + descripcion
        + "</div></html>"
        );

        jLabelDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        pack();
        
        setLocationRelativeTo(null);
        
    }

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAceptarActionPerformed
        this.dispose();
    }// GEN-LAST:event_jButtonAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelBoton;
    private javax.swing.JPanel jPanelTitulo;
    // End of variables declaration//GEN-END:variables
}
