/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas.administrador.internals.mesas;

import java.sql.SQLException;

import com.mycompany.javabeans_cafe.daos.MesaDAO;
import com.mycompany.javabeans_cafe.exceptions.NumeroInvalidoException;
import com.mycompany.javabeans_cafe.exceptions.TextoVacioException;
import com.mycompany.javabeans_cafe.interfaces_graficas.modales.MensajeDialogFrame;
import com.mycompany.javabeans_cafe.modelos.Mesa;
import com.mycompany.javabeans_cafe.util.RecolectorDeDatos;

/**
 *
 * @author matul
 */
public class InternalRegistrarMesa extends javax.swing.JInternalFrame {

    private RecolectorDeDatos recolector;
    private boolean errorEnRecolector;
    private int capacidadMesa;

    /**
     * Creates new form InternalRegistrarMesa
     */
    public InternalRegistrarMesa() {
        initComponents();

        this.errorEnRecolector = false;
    }

    private void recolectarDatosMesa() {
        this.errorEnRecolector = false;
        recolector = new RecolectorDeDatos();
        String mensajeError = "";

        try {
            this.capacidadMesa = recolector.recolectarEntero(jTextFieldCapacidad);

            if (capacidadMesa <= 0) {
                mensajeError = "La capacidad de la mesa debe ser mayor que cero.";
                mostrarMensajeErrorRecolector(mensajeError);
                return;
            }
        } catch (TextoVacioException e) {
            mensajeError = "El campo capacidad no puede estar vacio.";
            mostrarMensajeErrorRecolector(mensajeError);
            return;
        } catch (NumeroInvalidoException e) {
            mensajeError = "El campo capacidad contiene un número inválido.";
            mostrarMensajeErrorRecolector(mensajeError);
            return;
        }
    }

    private void mostrarMensajeErrorRecolector(String mensaje) {
        MensajeDialogFrame mensajeErrorFrame = new MensajeDialogFrame(null, true, mensaje, true);
        mensajeErrorFrame.setVisible(true);
        errorEnRecolector = true;
    }

    private void guardarMesa() {
        Mesa nuevaMesa = new Mesa(capacidadMesa);
        MesaDAO registradorMesa = new MesaDAO();

        try {
            registradorMesa.insertarMesa(nuevaMesa);
            String mensaje = "Mesa creada exitosamente.";
            MensajeDialogFrame mensajeExitoFrame = new MensajeDialogFrame(null, true, mensaje, false);
            mensajeExitoFrame.setVisible(true);
            limpiarCampos();
        } catch (SQLException e) {
            e.printStackTrace();
            String mensaje = "Error al crear la mesa: " + e.getMessage();
            MensajeDialogFrame mensajeErrorFrame = new MensajeDialogFrame(null, true, mensaje, true);
            mensajeErrorFrame.setVisible(true);
        }
    }

    private void limpiarCampos() {
        jTextFieldCapacidad.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelCentrado = new javax.swing.JPanel();
        jPanelFormulario = new javax.swing.JPanel();
        jPanelStockMinimo = new javax.swing.JPanel();
        jLabelCapacidad = new javax.swing.JLabel();
        jTextFieldCapacidad = new javax.swing.JTextField();
        jPanelBoton = new javax.swing.JPanel();
        jButtonRealizar = new javax.swing.JButton();

        jPanelTitulo.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTitulo.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTitulo.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Registrar Nueva Mesa");
        jLabelTitulo.setOpaque(true);
        jPanelTitulo.add(jLabelTitulo);

        getContentPane().add(jPanelTitulo, java.awt.BorderLayout.NORTH);

        jPanelCentrado.setBackground(new java.awt.Color(50, 52, 35));
        jPanelCentrado.setMinimumSize(new java.awt.Dimension(550, 343));
        jPanelCentrado.setPreferredSize(new java.awt.Dimension(550, 343));
        jPanelCentrado.setLayout(new java.awt.GridBagLayout());

        jPanelFormulario.setBackground(new java.awt.Color(50, 52, 35));
        jPanelFormulario.setLayout(new javax.swing.BoxLayout(jPanelFormulario, javax.swing.BoxLayout.Y_AXIS));

        jPanelStockMinimo.setBackground(new java.awt.Color(50, 52, 35));
        jPanelStockMinimo.setLayout(new java.awt.GridLayout(0, 1, 2, 5));

        jLabelCapacidad.setBackground(new java.awt.Color(50, 52, 35));
        jLabelCapacidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCapacidad.setText("Capacidad de la mesa");
        jLabelCapacidad.setOpaque(true);
        jPanelStockMinimo.add(jLabelCapacidad);

        jTextFieldCapacidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 135, 88)));
        jPanelStockMinimo.add(jTextFieldCapacidad);

        jPanelFormulario.add(jPanelStockMinimo);

        jPanelCentrado.add(jPanelFormulario, new java.awt.GridBagConstraints());

        getContentPane().add(jPanelCentrado, java.awt.BorderLayout.CENTER);

        jPanelBoton.setBackground(new java.awt.Color(50, 52, 35));

        jButtonRealizar.setBackground(new java.awt.Color(227, 135, 88));
        jButtonRealizar.setFont(new java.awt.Font("Noto Sans CJK JP Black", 0, 12)); // NOI18N
        jButtonRealizar.setText("Registrar mesa");
        jButtonRealizar.addActionListener(this::jButtonRealizarActionPerformed);
        jPanelBoton.add(jButtonRealizar);

        getContentPane().add(jPanelBoton, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRealizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRealizarActionPerformed
        recolectarDatosMesa();

        if (errorEnRecolector) {
            return;
        }

        guardarMesa();
    }// GEN-LAST:event_jButtonRealizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRealizar;
    private javax.swing.JLabel jLabelCapacidad;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelBoton;
    private javax.swing.JPanel jPanelCentrado;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JPanel jPanelStockMinimo;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JTextField jTextFieldCapacidad;
    // End of variables declaration//GEN-END:variables
}
