/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas.administrador.internals.mesas;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.swing.SwingUtilities;

import com.mycompany.javabeans_cafe.daos.MesaDAO;
import com.mycompany.javabeans_cafe.exceptions.NumeroInvalidoException;
import com.mycompany.javabeans_cafe.exceptions.TextoVacioException;
import com.mycompany.javabeans_cafe.interfaces_graficas.modales.MensajeDialogFrame;
import com.mycompany.javabeans_cafe.modelos.Mesa;
import com.mycompany.javabeans_cafe.util.RecolectorDeDatos;

/**
 *
 * @author matul
 */
public class InternalEditarMesa extends javax.swing.JInternalFrame {

    private RecolectorDeDatos recolector;
    private boolean errorEnRecolector;
    private int capacidadMesa;

    private List<Mesa> mesasCargadas = new ArrayList<>();
    private Mesa mesaSeleccionada;

    /**
     * Creates new form InternalEditarMesa
     */
    public InternalEditarMesa() {
        initComponents();

        jSplitPane1.setResizeWeight(0.3);

        SwingUtilities.invokeLater(() -> {
            jSplitPane1.setDividerLocation(0.3);
        });

        cargarMesas();
    }

    private void cargarMesas() {
        jComboBoxMesas.removeAllItems();
        mesasCargadas.clear();

        MesaDAO mesaDAO = new MesaDAO();

        try {
            List<Mesa> mesas = mesaDAO.obtenerTodos();
            mesasCargadas.addAll(mesas);
            for (Mesa mesa : mesas) {
                jComboBoxMesas.addItem(mesa.getNumeroMesa() + " - Capacidad: " + mesa.getCapacidad());
            }
        } catch (SQLException e) {
            String mensajeError = "Error al cargar mesas: " + e.getMessage();
            MensajeDialogFrame frameError = new MensajeDialogFrame(null, true, mensajeError, true);
            frameError.setVisible(true);
        }
    }

    private void recolectarDatosMesa() {
        this.errorEnRecolector = false;
        this.recolector = new RecolectorDeDatos();
        String mensajeError = "";

        try {
            this.capacidadMesa = recolector.recolectarEntero(jTextFieldCapacidad);

            if (capacidadMesa <= 0) {
                mensajeError = "La capacidad de la mesa debe ser mayor que cero.";
                mostrarMensajeErrorRecolector(mensajeError);
                return;
            }
        } catch (TextoVacioException e) {
            mensajeError = "El campo capacidad no puede estar vacio.";
            mostrarMensajeErrorRecolector(mensajeError);
            return;
        } catch (NumeroInvalidoException e) {
            mensajeError = "El campo capacidad contiene un número inválido.";
            mostrarMensajeErrorRecolector(mensajeError);
            return;
        }
    }

    private void cargarDatosMesaSeleccionada() {
        jTextFieldCapacidad.setText(String.valueOf(mesaSeleccionada.getCapacidad()));
    }

    private void limpiarCampos() {
        jTextFieldCapacidad.setText("");
    }

    private void mostrarMensajeErrorRecolector(String mensaje) {
        MensajeDialogFrame mensajeErrorFrame = new MensajeDialogFrame(null, true, mensaje, true);
        mensajeErrorFrame.setVisible(true);
        errorEnRecolector = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanelSeleccionador = new javax.swing.JPanel();
        jPanelTitulo1 = new javax.swing.JPanel();
        jLabelTituloSeleccionar = new javax.swing.JLabel();
        jPanelCentrado1 = new javax.swing.JPanel();
        jPanelFormulario1 = new javax.swing.JPanel();
        jPanelDPI13 = new javax.swing.JPanel();
        jLabelLista = new javax.swing.JLabel();
        jComboBoxMesas = new javax.swing.JComboBox<>();
        jPanelBoton1 = new javax.swing.JPanel();
        jButtonSeleccionar = new javax.swing.JButton();
        jPanelEditor = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelCentrado = new javax.swing.JPanel();
        jPanelFormulario = new javax.swing.JPanel();
        jPanelCantidad = new javax.swing.JPanel();
        jLabelCapacidad = new javax.swing.JLabel();
        jTextFieldCapacidad = new javax.swing.JTextField();
        jPanelBoton = new javax.swing.JPanel();
        jButtonRealizar = new javax.swing.JButton();

        jPanelSeleccionador.setLayout(new java.awt.BorderLayout());

        jPanelTitulo1.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTituloSeleccionar.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTituloSeleccionar.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTituloSeleccionar.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTituloSeleccionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloSeleccionar.setText("Seleccionar Mesa");
        jLabelTituloSeleccionar.setOpaque(true);
        jPanelTitulo1.add(jLabelTituloSeleccionar);

        jPanelSeleccionador.add(jPanelTitulo1, java.awt.BorderLayout.NORTH);

        jPanelCentrado1.setBackground(new java.awt.Color(50, 52, 35));
        jPanelCentrado1.setMinimumSize(new java.awt.Dimension(550, 343));
        jPanelCentrado1.setPreferredSize(new java.awt.Dimension(550, 343));
        jPanelCentrado1.setLayout(new java.awt.GridBagLayout());

        jPanelFormulario1.setBackground(new java.awt.Color(50, 52, 35));
        jPanelFormulario1.setLayout(new javax.swing.BoxLayout(jPanelFormulario1, javax.swing.BoxLayout.Y_AXIS));

        jPanelDPI13.setBackground(new java.awt.Color(50, 52, 35));
        jPanelDPI13.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jLabelLista.setBackground(new java.awt.Color(50, 52, 35));
        jLabelLista.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLista.setText("Elija una mesa");
        jLabelLista.setOpaque(true);
        jPanelDPI13.add(jLabelLista);

        jComboBoxMesas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxMesas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 135, 88)));
        jPanelDPI13.add(jComboBoxMesas);

        jPanelFormulario1.add(jPanelDPI13);

        jPanelCentrado1.add(jPanelFormulario1, new java.awt.GridBagConstraints());

        jPanelSeleccionador.add(jPanelCentrado1, java.awt.BorderLayout.CENTER);

        jPanelBoton1.setBackground(new java.awt.Color(50, 52, 35));

        jButtonSeleccionar.setBackground(new java.awt.Color(227, 135, 88));
        jButtonSeleccionar.setFont(new java.awt.Font("Noto Sans CJK JP Black", 0, 12)); // NOI18N
        jButtonSeleccionar.setText("Seleccionar");
        jButtonSeleccionar.addActionListener(this::jButtonSeleccionarActionPerformed);
        jPanelBoton1.add(jButtonSeleccionar);

        jPanelSeleccionador.add(jPanelBoton1, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setLeftComponent(jPanelSeleccionador);

        jPanelEditor.setLayout(new java.awt.BorderLayout());

        jPanelTitulo.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTitulo.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTitulo.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Editor Mesas");
        jLabelTitulo.setOpaque(true);
        jPanelTitulo.add(jLabelTitulo);

        jPanelEditor.add(jPanelTitulo, java.awt.BorderLayout.NORTH);

        jPanelCentrado.setBackground(new java.awt.Color(50, 52, 35));
        jPanelCentrado.setMinimumSize(new java.awt.Dimension(550, 343));
        jPanelCentrado.setPreferredSize(new java.awt.Dimension(550, 343));
        jPanelCentrado.setLayout(new java.awt.GridBagLayout());

        jPanelFormulario.setBackground(new java.awt.Color(50, 52, 35));
        jPanelFormulario.setLayout(new javax.swing.BoxLayout(jPanelFormulario, javax.swing.BoxLayout.Y_AXIS));

        jPanelCantidad.setBackground(new java.awt.Color(50, 52, 35));
        jPanelCantidad.setLayout(new java.awt.GridLayout(0, 1, 2, 5));

        jLabelCapacidad.setBackground(new java.awt.Color(50, 52, 35));
        jLabelCapacidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCapacidad.setText("Capacidad de la mesa");
        jLabelCapacidad.setOpaque(true);
        jPanelCantidad.add(jLabelCapacidad);

        jTextFieldCapacidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 135, 88)));
        jPanelCantidad.add(jTextFieldCapacidad);

        jPanelFormulario.add(jPanelCantidad);

        jPanelCentrado.add(jPanelFormulario, new java.awt.GridBagConstraints());

        jPanelEditor.add(jPanelCentrado, java.awt.BorderLayout.CENTER);

        jPanelBoton.setBackground(new java.awt.Color(50, 52, 35));

        jButtonRealizar.setBackground(new java.awt.Color(227, 135, 88));
        jButtonRealizar.setFont(new java.awt.Font("Noto Sans CJK JP Black", 0, 12)); // NOI18N
        jButtonRealizar.setText("Editar Mesa");
        jButtonRealizar.addActionListener(this::jButtonRealizarActionPerformed);
        jPanelBoton.add(jButtonRealizar);

        jPanelEditor.add(jPanelBoton, java.awt.BorderLayout.SOUTH);

        jSplitPane1.setRightComponent(jPanelEditor);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonSeleccionarActionPerformed
        int indiceSeleccionado = jComboBoxMesas.getSelectedIndex();

        if (indiceSeleccionado == -1) {
            return;
        }

        this.mesaSeleccionada = mesasCargadas.get(indiceSeleccionado);

        cargarDatosMesaSeleccionada();
    }// GEN-LAST:event_jButtonSeleccionarActionPerformed

    private void jButtonRealizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonRealizarActionPerformed
        if (mesaSeleccionada == null) {
            String mensajeError = "Debe seleccionar una mesa antes de editarla.";
            mostrarMensajeErrorRecolector(mensajeError);
            return;
        }

        recolectarDatosMesa();

        if (errorEnRecolector) {
            return;
        }

        MesaDAO mesaDAO = new MesaDAO();

        try {
            mesaDAO.actualizarCapacidad(mesaSeleccionada.getNumeroMesa(), capacidadMesa);
            mesaSeleccionada = null;
            String mensajeExito = "Mesa actualizada exitosamente.";
            MensajeDialogFrame frameExito = new MensajeDialogFrame(null, true, mensajeExito, false);
            frameExito.setVisible(true);
            limpiarCampos();
            cargarMesas();
        } catch (SQLException e) {
            String mensajeError = "Error al actualizar la mesa: " + e.getMessage();
            mostrarMensajeErrorRecolector(mensajeError);
        }
    }// GEN-LAST:event_jButtonRealizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRealizar;
    private javax.swing.JButton jButtonSeleccionar;
    private javax.swing.JComboBox<String> jComboBoxMesas;
    private javax.swing.JLabel jLabelCapacidad;
    private javax.swing.JLabel jLabelLista;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTituloSeleccionar;
    private javax.swing.JPanel jPanelBoton;
    private javax.swing.JPanel jPanelBoton1;
    private javax.swing.JPanel jPanelCantidad;
    private javax.swing.JPanel jPanelCentrado;
    private javax.swing.JPanel jPanelCentrado1;
    private javax.swing.JPanel jPanelDPI13;
    private javax.swing.JPanel jPanelEditor;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JPanel jPanelFormulario1;
    private javax.swing.JPanel jPanelSeleccionador;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JPanel jPanelTitulo1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextFieldCapacidad;
    // End of variables declaration//GEN-END:variables
}
