/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas.administrador.internals.mesas;

import com.mycompany.javabeans_cafe.enums.EstadoMesa;
import com.mycompany.javabeans_cafe.modelos.Mesa;

/**
 *
 * @author matul
 */
public class PanelMesa extends javax.swing.JPanel {

    private Mesa mesa;

    /**
     * Creates new form PanelMesa
     */
    public PanelMesa(Mesa mesa) {
        initComponents();
        this.mesa = mesa;
        insertarDatos();
        asignarColorLabelEstado();
    }

    private void insertarDatos() {
        jLabelNumeroMesa.setText("Numero Mesa: " + mesa.getNumeroMesa());
        jLabelTituloCapacidad.setText("Capacidad: " + mesa.getCapacidad());
        jLabelTituloEstado.setText("Estado: " + mesa.getEstado());
    }

    private void asignarColorLabelEstado() {
        if (mesa.getEstado() == EstadoMesa.LIBRE) {
            jLabelTituloEstado.setBackground(new java.awt.Color(45, 80, 60)); // fondo
        } else if (mesa.getEstado() == EstadoMesa.OCUPADA) {
            jLabelTituloEstado.setBackground(new java.awt.Color(105, 45, 45));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNumeroMesa = new javax.swing.JLabel();
        jLabelTituloCapacidad = new javax.swing.JLabel();
        jLabelTituloEstado = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(3, 1));

        jLabelNumeroMesa.setBackground(new java.awt.Color(50, 52, 35));
        jLabelNumeroMesa.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelNumeroMesa.setForeground(new java.awt.Color(227, 135, 88));
        jLabelNumeroMesa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumeroMesa.setText("Numero Mesa: xxxxx");
        jLabelNumeroMesa.setOpaque(true);
        add(jLabelNumeroMesa);

        jLabelTituloCapacidad.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTituloCapacidad.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTituloCapacidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloCapacidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloCapacidad.setText("Capacidad: xxxxx");
        jLabelTituloCapacidad.setOpaque(true);
        add(jLabelTituloCapacidad);

        jLabelTituloEstado.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTituloEstado.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTituloEstado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloEstado.setText("Estado: LIBRE");
        jLabelTituloEstado.setOpaque(true);
        add(jLabelTituloEstado);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelNumeroMesa;
    private javax.swing.JLabel jLabelTituloCapacidad;
    private javax.swing.JLabel jLabelTituloEstado;
    // End of variables declaration//GEN-END:variables
}
