/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas;

import com.mycompany.javabeans_cafe.daos.EmpleadoDAO;
import com.mycompany.javabeans_cafe.enums.EmpleadoRol;
import com.mycompany.javabeans_cafe.exceptions.TextoVacioException;
import com.mycompany.javabeans_cafe.interfaces_graficas.administrador.AdminPrincipal;
import com.mycompany.javabeans_cafe.interfaces_graficas.barista.BaristaPrincipalFrame;
import com.mycompany.javabeans_cafe.interfaces_graficas.cocina.CocinaPrincipalFrame;
import com.mycompany.javabeans_cafe.interfaces_graficas.mesero.MeseroPrincipalFrame;
import com.mycompany.javabeans_cafe.interfaces_graficas.modales.MensajeDialogFrame;
import com.mycompany.javabeans_cafe.modelos.Empleado;
import com.mycompany.javabeans_cafe.util.RecolectorDeDatos;

/**
 *
 * @author matul
 */
public class LoginFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(LoginFrame.class.getName());

    private RecolectorDeDatos recolector;
    private boolean errorEnRecolector;
    private boolean errorEnUsuario;
    private boolean errorEnContrasenia;
    private boolean errorEnValidacion;
    private String nombreUsuario;
    private String contrasenia;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldEmpleado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordFieldContrasenia = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jButtonIngresar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(50, 52, 35));

        jPanel1.setBackground(new java.awt.Color(50, 52, 35));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        jPanel3.setBackground(new java.awt.Color(50, 52, 35));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);

        jPanel2.setBackground(new java.awt.Color(50, 52, 35));
        jPanel2.setLayout(new java.awt.GridLayout(10, 1, 0, 10));

        jPanel5.setBackground(new java.awt.Color(50, 52, 35));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);

        jLabel4.setBackground(new java.awt.Color(50, 52, 35));
        jLabel4.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(227, 135, 88));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inicio de Sesion");
        jLabel4.setOpaque(true);
        jPanel2.add(jLabel4);

        jPanel8.setBackground(new java.awt.Color(50, 52, 35));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8);

        jLabel1.setBackground(new java.awt.Color(50, 52, 35));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario (nombre de usuario o DPI)");
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1);
        jPanel2.add(jTextFieldEmpleado);

        jLabel2.setBackground(new java.awt.Color(50, 52, 35));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contrasenia");
        jLabel2.setOpaque(true);
        jPanel2.add(jLabel2);
        jPanel2.add(jPasswordFieldContrasenia);

        jLabel3.setBackground(new java.awt.Color(50, 52, 35));
        jLabel3.setOpaque(true);
        jPanel2.add(jLabel3);

        jButtonIngresar.setBackground(new java.awt.Color(227, 135, 88));
        jButtonIngresar.setFont(new java.awt.Font("Noto Sans CJK JP Black", 0, 12)); // NOI18N
        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.addActionListener(this::jButtonIngresarActionPerformed);
        jPanel2.add(jButtonIngresar);

        jPanel6.setBackground(new java.awt.Color(50, 52, 35));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2);

        jPanel4.setBackground(new java.awt.Color(50, 52, 35));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 258, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recolectarDatosUsuario() {
        this.errorEnRecolector = false;
        recolector = new RecolectorDeDatos();
        String mensajeError = "";

        try {
            this.nombreUsuario = recolector.recolectarTexto(jTextFieldEmpleado);
        } catch (TextoVacioException e) {
            errorEnUsuario = true;
            mensajeError = "El campo nombre de usuario no puede estar vacio.";
        }

        try {
            this.contrasenia = recolector.recolectarTexto(jPasswordFieldContrasenia);
        } catch (TextoVacioException e) {
            errorEnContrasenia = true;
            mensajeError = "El campo contraseña no puede estar vacio.";
        }

        if (errorEnRecolector) {
            if (errorEnUsuario && errorEnContrasenia) {
                mensajeError = "Por favor, complete todos los campos requeridos.";
            }

            mostrarMensajeErrorRecolector(mensajeError);
        }

    }

    private void verificarCredenciales() {
        String usuarioNombre = jTextFieldEmpleado.getText();
        String password = new String(jPasswordFieldContrasenia.getPassword());
        EmpleadoDAO empleadoDAO = new EmpleadoDAO();

        try {
            Empleado empleado = empleadoDAO.encontrarPorNombreUsuario(usuarioNombre);

            if (empleado == null) {
                empleado = empleadoDAO.encontrarPorDPI(usuarioNombre);
            }

            if (empleado != null && empleado.getContrasena().equals(password)) {

                // Credenciales válidas, abrir la ventana principal
                if (empleado.getRol() == EmpleadoRol.ADMINISTRADOR) {
                    AdminPrincipal administradorFrame = new AdminPrincipal();
                    administradorFrame.setVisible(true);
                    this.dispose();
                } else if (empleado.getRol() == EmpleadoRol.BARISTA) {
                    BaristaPrincipalFrame baristaFrame = new BaristaPrincipalFrame();
                    baristaFrame.setVisible(true);
                    this.dispose();
                } else if (empleado.getRol() == EmpleadoRol.COCINA) {
                    CocinaPrincipalFrame cocinaFrame = new CocinaPrincipalFrame();
                    cocinaFrame.setVisible(true);
                    this.dispose();
                } else if (empleado.getRol() == EmpleadoRol.MESERO) {
                    MeseroPrincipalFrame meseroFrame = new MeseroPrincipalFrame();
                    meseroFrame.setVisible(true);
                    this.dispose();
                }
            } else {
                String mensajeError = "Usuario o contraseña incorrectos.";
                MensajeDialogFrame mensajeErrorFrame = new MensajeDialogFrame(null, true, mensajeError);
                mensajeErrorFrame.setVisible(true);
            }
        } catch (Exception e) {
            String mensajeError = "Error al validar credenciales: " + e.getMessage();
            MensajeDialogFrame mensajeErrorFrame = new MensajeDialogFrame(null, true, mensajeError);
            mensajeErrorFrame.setVisible(true);
        }

    }

    private void mostrarMensajeErrorRecolector(String mensaje) {
        MensajeDialogFrame mensajeErrorFrame = new MensajeDialogFrame(null, true, mensaje);
        mensajeErrorFrame.setVisible(true);
        errorEnRecolector = true;
    }

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonIngresarActionPerformed

        this.recolectarDatosUsuario();
        if (!errorEnRecolector) {
            this.verificarCredenciales();
        }
    }// GEN-LAST:event_jButtonIngresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordFieldContrasenia;
    private javax.swing.JTextField jTextFieldEmpleado;
    // End of variables declaration//GEN-END:variables
}
