/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas;

import com.mycompany.javabeans_cafe.daos.EmpleadoDAO;
import com.mycompany.javabeans_cafe.enums.EmpleadoRol;
import com.mycompany.javabeans_cafe.exceptions.TextoVacioException;
import com.mycompany.javabeans_cafe.interfaces_graficas.administrador.AdminPrincipal;
import com.mycompany.javabeans_cafe.interfaces_graficas.barista.BaristaPrincipalFrame;
import com.mycompany.javabeans_cafe.interfaces_graficas.cocina.CocinaPrincipalFrame;
import com.mycompany.javabeans_cafe.interfaces_graficas.mesero.MeseroPrincipalFrame;
import com.mycompany.javabeans_cafe.interfaces_graficas.modales.MensajeDialogFrame;
import com.mycompany.javabeans_cafe.modelos.Empleado;
import com.mycompany.javabeans_cafe.util.RecolectorDeDatos;

/**
 *
 * @author matul
 */
public class LoginFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(LoginFrame.class.getName());

    private RecolectorDeDatos recolector;
    private boolean errorEnRecolector;
    private boolean errorEnUsuario;
    private boolean errorEnContrasenia;
    private String credencialIngresada;
    private String contrasenia;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();

        setTitle("Inicio");
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelFormulario = new javax.swing.JPanel();
        jPanelUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldEmpleado = new javax.swing.JTextField();
        jPanelContrasena = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordFieldContrasenia = new javax.swing.JPasswordField();
        jPanelBoton = new javax.swing.JPanel();
        jButtonIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(50, 52, 35));

        jPanelTitulo.setBackground(new java.awt.Color(50, 52, 35));

        jLabel4.setBackground(new java.awt.Color(50, 52, 35));
        jLabel4.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(227, 135, 88));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inicio de Sesion");
        jLabel4.setOpaque(true);
        jPanelTitulo.add(jLabel4);

        getContentPane().add(jPanelTitulo, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(50, 52, 35));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanelFormulario.setBackground(new java.awt.Color(50, 52, 35));
        jPanelFormulario.setLayout(new javax.swing.BoxLayout(jPanelFormulario, javax.swing.BoxLayout.Y_AXIS));

        jPanelUsuario.setBackground(new java.awt.Color(50, 52, 35));
        jPanelUsuario.setLayout(new java.awt.GridLayout(2, 1));

        jLabel1.setBackground(new java.awt.Color(50, 52, 35));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario (nombre de usuario o DPI)");
        jLabel1.setOpaque(true);
        jPanelUsuario.add(jLabel1);

        jTextFieldEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 135, 88)));
        jPanelUsuario.add(jTextFieldEmpleado);

        jPanelFormulario.add(jPanelUsuario);

        jPanelContrasena.setBackground(new java.awt.Color(50, 52, 35));
        jPanelContrasena.setLayout(new java.awt.GridLayout(2, 1));

        jLabel2.setBackground(new java.awt.Color(50, 52, 35));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contrasenia");
        jLabel2.setOpaque(true);
        jPanelContrasena.add(jLabel2);

        jPasswordFieldContrasenia
                .setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 135, 88)));
        jPanelContrasena.add(jPasswordFieldContrasenia);

        jPanelFormulario.add(jPanelContrasena);

        jPanel2.add(jPanelFormulario, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanelBoton.setBackground(new java.awt.Color(50, 52, 35));

        jButtonIngresar.setBackground(new java.awt.Color(227, 135, 88));
        jButtonIngresar.setFont(new java.awt.Font("Noto Sans CJK JP Black", 0, 12)); // NOI18N
        jButtonIngresar.setText("Ingresar");
        jButtonIngresar.addActionListener(this::jButtonIngresarActionPerformed);
        jPanelBoton.add(jButtonIngresar);

        getContentPane().add(jPanelBoton, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recolectarDatosUsuario() {
        this.errorEnRecolector = false;
        this.errorEnUsuario = false;
        this.errorEnContrasenia = false;
        recolector = new RecolectorDeDatos();
        String mensajeError = "";

        try {
            this.credencialIngresada = recolector.recolectarTexto(jTextFieldEmpleado);
        } catch (TextoVacioException e) {
            errorEnUsuario = true;
            errorEnRecolector = true;
            mensajeError = "El campo nombre de usuario no puede estar vacio.";
            System.out.println("Entro en nombre vacio exception");
        }

        try {
            this.contrasenia = recolector.recolectarTexto(jPasswordFieldContrasenia);
        } catch (TextoVacioException e) {
            errorEnContrasenia = true;
            errorEnRecolector = true;
            mensajeError = "El campo contraseña no puede estar vacio.";
            System.out.println("Entro en contrasenia vacio exception");
        }

        if (errorEnRecolector) {
            if (errorEnUsuario && errorEnContrasenia) {
                mensajeError = "Por favor, complete todos los campos requeridos.";
                System.out.println("Ambos campos vacios");
            }

            mostrarMensajeErrorRecolector(mensajeError);
        }

    }

    private void verificarCredenciales() {
        EmpleadoDAO empleadoDAO = new EmpleadoDAO();

        try {
            Empleado empleado = empleadoDAO.encontrarPorNombreUsuario(credencialIngresada);

            if (empleado != null && empleado.isActivo() == false) {
                String mensajeError = "El usuario ha sido desactivado. Por favor, contacte al administrador.";
                MensajeDialogFrame mensajeErrorFrame = new MensajeDialogFrame(null, true, mensajeError, true);
                mensajeErrorFrame.setVisible(true);
                return;
            }

            if (empleado == null) {
                empleado = empleadoDAO.encontrarPorDPI(credencialIngresada);
            }

            if (empleado != null && empleado.getContrasena().equals(contrasenia)) {

                // Credenciales válidas, abrir la ventana principal
                if (empleado.getRol() == EmpleadoRol.ADMINISTRADOR) {
                    AdminPrincipal administradorFrame = new AdminPrincipal();
                    administradorFrame.setVisible(true);
                    this.dispose();
                } else if (empleado.getRol() == EmpleadoRol.BARISTA) {
                    BaristaPrincipalFrame baristaFrame = new BaristaPrincipalFrame();
                    baristaFrame.setVisible(true);
                    this.dispose();
                } else if (empleado.getRol() == EmpleadoRol.COCINA) {
                    CocinaPrincipalFrame cocinaFrame = new CocinaPrincipalFrame();
                    cocinaFrame.setVisible(true);
                    this.dispose();
                } else if (empleado.getRol() == EmpleadoRol.MESERO) {
                    MeseroPrincipalFrame meseroFrame = new MeseroPrincipalFrame();
                    meseroFrame.setVisible(true);
                    this.dispose();
                }
            } else {
                String mensajeError = "Usuario o contraseña incorrectos.";
                MensajeDialogFrame mensajeErrorFrame = new MensajeDialogFrame(null, true, mensajeError, true);
                mensajeErrorFrame.setVisible(true);
            }
        } catch (Exception e) {
            String mensajeError = "Error al validar credenciales: " + e.getMessage();
            MensajeDialogFrame mensajeErrorFrame = new MensajeDialogFrame(null, true, mensajeError, true);
            mensajeErrorFrame.setVisible(true);
        }

    }

    private void mostrarMensajeErrorRecolector(String mensaje) {
        MensajeDialogFrame mensajeErrorFrame = new MensajeDialogFrame(null, true, mensaje, true);
        mensajeErrorFrame.setVisible(true);
        errorEnRecolector = true;
    }

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonIngresarActionPerformed

        this.recolectarDatosUsuario();
        if (!errorEnRecolector) {
            this.verificarCredenciales();
        }
    }// GEN-LAST:event_jButtonIngresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBoton;
    private javax.swing.JPanel jPanelContrasena;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JPanel jPanelUsuario;
    private javax.swing.JPasswordField jPasswordFieldContrasenia;
    private javax.swing.JTextField jTextFieldEmpleado;
    // End of variables declaration//GEN-END:variables
}
