/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas.administrador.internals.gestion_empleados;

import com.mycompany.javabeans_cafe.daos.EmpleadoDAO;
import com.mycompany.javabeans_cafe.enums.EmpleadoRol;
import com.mycompany.javabeans_cafe.interfaces_graficas.modales.MensajeDialogFrame;
import com.mycompany.javabeans_cafe.modelos.Empleado;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author matul
 */
public class InternalDesactivarEmpleado extends javax.swing.JInternalFrame {

    private List<Empleado> empleadosCargados = new ArrayList<>();
    private Empleado empleadoSeleccionado;
    private boolean estadoSeleccionado;

    /**
     * Creates new form InternalDesactivarEmpleado
     */
    public InternalDesactivarEmpleado() {
        initComponents();

        cargarEstados();
        cargarEmpleados();
    }

    private void cargarEmpleados() {
        jComboBoxEmpleados.removeAllItems();
        empleadosCargados.clear();

        EmpleadoDAO empleadoDAO = new EmpleadoDAO();

        try {
            List<Empleado> empleados = empleadoDAO.obtenerTodosExceptoRol(EmpleadoRol.ADMINISTRADOR);
            empleadosCargados.addAll(empleados);
            for (Empleado empleado : empleados) {
                String estado = empleado.isActivo() ? "Activo" : "Inactivo";
                jComboBoxEmpleados.addItem(empleado.getDpi() + " - " + empleado.getNombreUsuario() + " - " + estado);
            }
        } catch (SQLException e) {
            String mensajeError = "Error al cargar empleados: " + e.getMessage();
            MensajeDialogFrame frameError = new MensajeDialogFrame(null, true, mensajeError, true);
            frameError.setVisible(true);
        }

    }

    private void cargarEstados() {
        jComboBoxEstados.removeAllItems();
        jComboBoxEstados.addItem("Activo");
        jComboBoxEstados.addItem("Inactivo");
    }

    private void seleccionarEmpleado() {
        int indiceSeleccionado = jComboBoxEmpleados.getSelectedIndex();
        this.empleadoSeleccionado = empleadosCargados.get(indiceSeleccionado);
    }

    private void seleccionarEstado() {
        int indiceSeleccionado = jComboBoxEstados.getSelectedIndex();
        this.estadoSeleccionado = (indiceSeleccionado == 0); // 0: Activo 1: Inactivo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelCentrado = new javax.swing.JPanel();
        jPanelFormulario = new javax.swing.JPanel();
        jPanelEmpleados = new javax.swing.JPanel();
        jLabelElija = new javax.swing.JLabel();
        jComboBoxEmpleados = new javax.swing.JComboBox<>();
        jPanelEmpleados1 = new javax.swing.JPanel();
        jLabelElija1 = new javax.swing.JLabel();
        jComboBoxEstados = new javax.swing.JComboBox<>();
        jPanelBoton = new javax.swing.JPanel();
        jButtonActualizar = new javax.swing.JButton();

        jPanelTitulo.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTitulo.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTitulo.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Activar / Desactivar Empleado");
        jLabelTitulo.setOpaque(true);
        jPanelTitulo.add(jLabelTitulo);

        getContentPane().add(jPanelTitulo, java.awt.BorderLayout.NORTH);

        jPanelCentrado.setBackground(new java.awt.Color(50, 52, 35));
        jPanelCentrado.setMinimumSize(new java.awt.Dimension(550, 343));
        jPanelCentrado.setPreferredSize(new java.awt.Dimension(550, 343));
        jPanelCentrado.setLayout(new java.awt.GridBagLayout());

        jPanelFormulario.setBackground(new java.awt.Color(50, 52, 35));
        jPanelFormulario.setLayout(new javax.swing.BoxLayout(jPanelFormulario, javax.swing.BoxLayout.Y_AXIS));

        jPanelEmpleados.setBackground(new java.awt.Color(50, 52, 35));
        jPanelEmpleados.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jLabelElija.setBackground(new java.awt.Color(50, 52, 35));
        jLabelElija.setForeground(new java.awt.Color(255, 255, 255));
        jLabelElija.setText("Elija un empleado");
        jLabelElija.setOpaque(true);
        jPanelEmpleados.add(jLabelElija);

        jComboBoxEmpleados.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEmpleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 135, 88)));
        jPanelEmpleados.add(jComboBoxEmpleados);

        jPanelFormulario.add(jPanelEmpleados);

        jPanelEmpleados1.setBackground(new java.awt.Color(50, 52, 35));
        jPanelEmpleados1.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jLabelElija1.setBackground(new java.awt.Color(50, 52, 35));
        jLabelElija1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelElija1.setText("Elija un estado");
        jLabelElija1.setOpaque(true);
        jPanelEmpleados1.add(jLabelElija1);

        jComboBoxEstados.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxEstados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 135, 88)));
        jPanelEmpleados1.add(jComboBoxEstados);

        jPanelFormulario.add(jPanelEmpleados1);

        jPanelCentrado.add(jPanelFormulario, new java.awt.GridBagConstraints());

        getContentPane().add(jPanelCentrado, java.awt.BorderLayout.CENTER);

        jPanelBoton.setBackground(new java.awt.Color(50, 52, 35));

        jButtonActualizar.setBackground(new java.awt.Color(227, 135, 88));
        jButtonActualizar.setFont(new java.awt.Font("Noto Sans CJK JP Black", 0, 12)); // NOI18N
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(this::jButtonActualizarActionPerformed);
        jPanelBoton.add(jButtonActualizar);

        getContentPane().add(jPanelBoton, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonActualizarActionPerformed
        seleccionarEmpleado();
        seleccionarEstado();
        EmpleadoDAO empleadoDAO = new EmpleadoDAO();

        try {
            empleadoDAO.actualizarEstadoEmpleado(empleadoSeleccionado.getCodigoEmpleado(), estadoSeleccionado);
            empleadoSeleccionado = null;
            cargarEmpleados();
            String mensajeExito = "Estado de empleado actualizado exitosamente.";
            MensajeDialogFrame frameExito = new MensajeDialogFrame(null, true, mensajeExito, false);
            frameExito.setVisible(true);
        } catch (SQLException e) {
            String mensajeError = "Error al actualizar el estado del empleado: " + e.getMessage();
            MensajeDialogFrame frameError = new MensajeDialogFrame(null, true, mensajeError, true);
            frameError.setVisible(true);
        }
    }// GEN-LAST:event_jButtonActualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JComboBox<String> jComboBoxEmpleados;
    private javax.swing.JComboBox<String> jComboBoxEstados;
    private javax.swing.JLabel jLabelElija;
    private javax.swing.JLabel jLabelElija1;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelBoton;
    private javax.swing.JPanel jPanelCentrado;
    private javax.swing.JPanel jPanelEmpleados;
    private javax.swing.JPanel jPanelEmpleados1;
    private javax.swing.JPanel jPanelFormulario;
    private javax.swing.JPanel jPanelTitulo;
    // End of variables declaration//GEN-END:variables
}
