/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas.administrador.internals.gestion_empleados;

import java.sql.SQLException;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import com.mycompany.javabeans_cafe.daos.EmpleadoDAO;
import com.mycompany.javabeans_cafe.interfaces_graficas.modales.MensajeDialogFrame;
import com.mycompany.javabeans_cafe.modelos.Empleado;

/**
 *
 * @author matul
 */
public class InternalListaEmpleados extends javax.swing.JInternalFrame {

    private List<Empleado> empleadosActivos;
    private List<Empleado> empleadosInactivos;
    private EmpleadoDAO empleadoDAO;

    /**
     * Creates new form InternalListaEmpleados
     */
    public InternalListaEmpleados() {
        initComponents();
        empleadoDAO = new EmpleadoDAO();
        cargarEmpleadosActivos();
        cargarEmpleadosInactivos();
        colocarEmpleadosEnTabla();
    }

    private void cargarEmpleadosActivos() {
        try {
            this.empleadosActivos = empleadoDAO.obtenerTodos(true);
        } catch (SQLException e) {
            String mensajeError = "Error al cargar los empleados activos: " + e.getMessage();
            MensajeDialogFrame mensajeDialogFrame = new MensajeDialogFrame(null, true, mensajeError, true);
            mensajeDialogFrame.setVisible(true);
        }

    }

    private void cargarEmpleadosInactivos() {
        try {
            this.empleadosInactivos = empleadoDAO.obtenerTodos(false);
        } catch (SQLException e) {
            String mensajeError = "Error al cargar los empleados inactivos: " + e.getMessage();
            MensajeDialogFrame mensajeDialogFrame = new MensajeDialogFrame(null, true, mensajeError, true);
            mensajeDialogFrame.setVisible(true);
        }
    }

    private void colocarEmpleadosEnTabla() {

        String[] columnas = {
                "Código",
                "DPI",
                "Nombre completo",
                "Usuario",
                "Rol",
                "Jornada laboral",
                "Salario",
                "Fecha de contratación",
                "Activo"
        };

        DefaultTableModel modeloActivos = crearModelo(columnas);
        DefaultTableModel modeloInactivos = crearModelo(columnas);

        if (empleadosActivos != null) {
            for (Empleado empleado : empleadosActivos) {
                modeloActivos.addRow(convertirEmpleadoAFila(empleado));
            }
        }

        if (empleadosInactivos != null) {
            for (Empleado empleado : empleadosInactivos) {
                modeloInactivos.addRow(convertirEmpleadoAFila(empleado));
            }
        }

        jTableActivos.setModel(modeloActivos);
        jTableInactivos.setModel(modeloInactivos);
    }

    private DefaultTableModel crearModelo(String[] columnas) {
        return new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
    }

    private Object[] convertirEmpleadoAFila(Empleado empleado) {
        return new Object[] {
                empleado.getCodigoEmpleado(),
                empleado.getDpi(),
                empleado.getNombreCompleto(),
                empleado.getNombreUsuario(),
                empleado.getRol(),
                empleado.getJornadaLaboral(),
                empleado.getSalario(),
                empleado.getFechaContratacion(),
                empleado.isActivo() ? "Sí" : "No"
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelTituloListas = new javax.swing.JLabel();
        jPanelTablas = new javax.swing.JPanel();
        jPanelAjuste = new javax.swing.JPanel();
        jPanelTablaUno = new javax.swing.JPanel();
        jPanelTituloTablaUno = new javax.swing.JPanel();
        jLabelTituloActivos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableActivos = new javax.swing.JTable();
        jPanelTablaDos = new javax.swing.JPanel();
        jPanelTituloTablaUno1 = new javax.swing.JPanel();
        jLabelTituloInactivos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableInactivos = new javax.swing.JTable();

        setBackground(new java.awt.Color(50, 52, 35));

        jPanel1.setBackground(new java.awt.Color(50, 52, 35));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanelTitulo.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTituloListas.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTituloListas.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTituloListas.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTituloListas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloListas.setText("Lista de Empleados");
        jLabelTituloListas.setOpaque(true);
        jPanelTitulo.add(jLabelTituloListas);

        jPanel1.add(jPanelTitulo, java.awt.BorderLayout.NORTH);

        jPanelTablas.setBackground(new java.awt.Color(50, 52, 35));
        jPanelTablas.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 15, 20));
        jPanelTablas.setLayout(new java.awt.BorderLayout());

        jPanelAjuste.setLayout(new java.awt.GridLayout(2, 1, 15, 0));

        jPanelTablaUno.setBackground(new java.awt.Color(50, 52, 35));
        jPanelTablaUno.setLayout(new java.awt.BorderLayout());

        jPanelTituloTablaUno.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTituloActivos.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTituloActivos.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTituloActivos.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTituloActivos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloActivos.setText("Activos");
        jLabelTituloActivos.setOpaque(true);
        jPanelTituloTablaUno.add(jLabelTituloActivos);

        jPanelTablaUno.add(jPanelTituloTablaUno, java.awt.BorderLayout.NORTH);

        jTableActivos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(jTableActivos);

        jPanelTablaUno.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelAjuste.add(jPanelTablaUno);

        jPanelTablaDos.setBackground(new java.awt.Color(50, 52, 35));
        jPanelTablaDos.setLayout(new java.awt.BorderLayout());

        jPanelTituloTablaUno1.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTituloInactivos.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTituloInactivos.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTituloInactivos.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTituloInactivos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloInactivos.setText("Inactivos");
        jLabelTituloInactivos.setOpaque(true);
        jPanelTituloTablaUno1.add(jLabelTituloInactivos);

        jPanelTablaDos.add(jPanelTituloTablaUno1, java.awt.BorderLayout.NORTH);

        jTableInactivos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane2.setViewportView(jTableInactivos);

        jPanelTablaDos.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanelAjuste.add(jPanelTablaDos);

        jPanelTablas.add(jPanelAjuste, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelTablas, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTituloActivos;
    private javax.swing.JLabel jLabelTituloInactivos;
    private javax.swing.JLabel jLabelTituloListas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAjuste;
    private javax.swing.JPanel jPanelTablaDos;
    private javax.swing.JPanel jPanelTablaUno;
    private javax.swing.JPanel jPanelTablas;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JPanel jPanelTituloTablaUno;
    private javax.swing.JPanel jPanelTituloTablaUno1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableActivos;
    private javax.swing.JTable jTableInactivos;
    // End of variables declaration//GEN-END:variables
}
