/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas.administrador.nomina;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import com.mycompany.javabeans_cafe.daos.BalanceFinancieroDAO;
import com.mycompany.javabeans_cafe.interfaces_graficas.modales.MensajeDialogFrame;
import com.mycompany.javabeans_cafe.modelos.BalanceFinanciero;

/**
 *
 * @author matul
 */
public class InternalVisualizadorBalances extends javax.swing.JInternalFrame {

    private List<BalanceFinanciero> balancesFinancieros;
    private BalanceFinanciero ultimoBalanceFinanciero;

    /**
     * Creates new form InternalVisualizadorNominas
     */
    public InternalVisualizadorBalances() {
        initComponents();
        cargarBalanceFinanciero();
        cargarTablaTodosLosBalances();
        cargarTablaUltimoBalance();
    }

    private void cargarBalanceFinanciero() {
        BalanceFinancieroDAO balanceFinancieroDAO = new BalanceFinancieroDAO();
        try {
            this.balancesFinancieros = balanceFinancieroDAO.obtenerTodos();
            this.ultimoBalanceFinanciero = balanceFinancieroDAO.obtenerUltimo();
        } catch (SQLException e) {
            String mensajeError = "Error al cargar los balances financieros: " + e.getMessage();
            mostrarError(mensajeError);
        }

    }

    private void cargarTablaTodosLosBalances() {
        String[] columnas = {
                "Id balance",
                "Fecha y hora",
                "Monto ingresos",
                "Monto egresos",
                "Balance",
                "Descripción balance",
        };

        DefaultTableModel modeloInsumos = crearModelo(columnas);

        if (this.balancesFinancieros != null) {
            for (BalanceFinanciero balance : this.balancesFinancieros) {
                modeloInsumos.addRow(convertirBalanceAFila(balance));
            }
        }

        jTableActivos.setModel(modeloInsumos);
    }

    private void cargarTablaUltimoBalance() {
        String[] columnas = {
                "Id balance",
                "Fecha y hora",
                "Monto ingresos",
                "Monto egresos",
                "Balance",
                "Descripción balance",
        };

        DefaultTableModel modeloInsumos = crearModelo(columnas);

        if (this.ultimoBalanceFinanciero != null) {
            modeloInsumos.addRow(convertirBalanceAFila(this.ultimoBalanceFinanciero));
        }

        jTableInactivos.setModel(modeloInsumos);
    }

    private DefaultTableModel crearModelo(String[] columnas) {
        return new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
    }

    private Object[] convertirBalanceAFila(BalanceFinanciero balance) {
        String descripcion = "";

        if (balance.getBalance().compareTo(BigDecimal.ZERO) < 0) {
            descripcion = "PÉRDIDA";
        } else if (balance.getBalance().compareTo(BigDecimal.ZERO) > 0) {
            descripcion = "GANANCIA";
        } else {
            descripcion = "BALANCE NEUTRO";
        }

        return new Object[] {
                balance.getId(),
                balance.getFechaHora(),
                "Q. " + balance.getMontoIngresos(),
                "Q. " + balance.getMontoEgresos(),
                "Q. " + balance.getBalance(),
                descripcion
        };
    }

    private void mostrarError(String mensaje) {
        MensajeDialogFrame mensajeDialogFrame = new MensajeDialogFrame(null, true, mensaje, true);
        mensajeDialogFrame.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelTituloListas = new javax.swing.JLabel();
        jPanelTablas = new javax.swing.JPanel();
        jPanelAjuste = new javax.swing.JPanel();
        jPanelTablaUno = new javax.swing.JPanel();
        jPanelTituloTablaUno = new javax.swing.JPanel();
        jLabelTituloTodos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableActivos = new javax.swing.JTable();
        jPanelTablaDos = new javax.swing.JPanel();
        jPanelTituloTablaUno1 = new javax.swing.JPanel();
        jLabelTituloUltimo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableInactivos = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(50, 52, 35));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanelTitulo.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTituloListas.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTituloListas.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTituloListas.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTituloListas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloListas.setText("Lista de Balances");
        jLabelTituloListas.setOpaque(true);
        jPanelTitulo.add(jLabelTituloListas);

        jPanel1.add(jPanelTitulo, java.awt.BorderLayout.NORTH);

        jPanelTablas.setBackground(new java.awt.Color(50, 52, 35));
        jPanelTablas.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 15, 20));
        jPanelTablas.setLayout(new java.awt.BorderLayout());

        jPanelAjuste.setLayout(new java.awt.GridLayout(2, 1, 15, 0));

        jPanelTablaUno.setBackground(new java.awt.Color(50, 52, 35));
        jPanelTablaUno.setLayout(new java.awt.BorderLayout());

        jPanelTituloTablaUno.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTituloTodos.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTituloTodos.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTituloTodos.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTituloTodos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloTodos.setText("Todos los balances");
        jLabelTituloTodos.setOpaque(true);
        jPanelTituloTablaUno.add(jLabelTituloTodos);

        jPanelTablaUno.add(jPanelTituloTablaUno, java.awt.BorderLayout.NORTH);

        jTableActivos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(jTableActivos);

        jPanelTablaUno.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanelAjuste.add(jPanelTablaUno);

        jPanelTablaDos.setBackground(new java.awt.Color(50, 52, 35));
        jPanelTablaDos.setLayout(new java.awt.BorderLayout());

        jPanelTituloTablaUno1.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTituloUltimo.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTituloUltimo.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTituloUltimo.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTituloUltimo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloUltimo.setText("Ultimo balance registrado");
        jLabelTituloUltimo.setOpaque(true);
        jPanelTituloTablaUno1.add(jLabelTituloUltimo);

        jPanelTablaDos.add(jPanelTituloTablaUno1, java.awt.BorderLayout.NORTH);

        jTableInactivos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane2.setViewportView(jTableInactivos);

        jPanelTablaDos.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanelAjuste.add(jPanelTablaDos);

        jPanelTablas.add(jPanelAjuste, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanelTablas, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTituloListas;
    private javax.swing.JLabel jLabelTituloTodos;
    private javax.swing.JLabel jLabelTituloUltimo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAjuste;
    private javax.swing.JPanel jPanelTablaDos;
    private javax.swing.JPanel jPanelTablaUno;
    private javax.swing.JPanel jPanelTablas;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JPanel jPanelTituloTablaUno;
    private javax.swing.JPanel jPanelTituloTablaUno1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableActivos;
    private javax.swing.JTable jTableInactivos;
    // End of variables declaration//GEN-END:variables
}
