/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.javabeans_cafe.interfaces_graficas.administrador.internal.reportes;

import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;

import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

import com.mycompany.javabeans_cafe.daos.ProductoMasVendidoDAO;
import com.mycompany.javabeans_cafe.interfaces_graficas.modales.MensajeDialogFrame;
import com.mycompany.javabeans_cafe.modelos.ProductoMasVendido;
import com.mycompany.javabeans_cafe.util.ExportadorBalanceHTML;
import com.mycompany.javabeans_cafe.util.ExportadorProctoTopHTML;

/**
 *
 * @author matul
 */
public class InternalProductosMasVendidos extends javax.swing.JInternalFrame {

    private List<ProductoMasVendido> productosMasVendidos;

    /**
     * Creates new form InternalProductosMasVendidos
     */
    public InternalProductosMasVendidos() {
        initComponents();
        cargarProductosMasVendidos();
        colocarProductosEnTabla();
    }

    private void cargarProductosMasVendidos() {
        ProductoMasVendidoDAO productoMasVendidoDAO = new ProductoMasVendidoDAO();
        try {
            this.productosMasVendidos = productoMasVendidoDAO.obtenerProductosMasVendidos();
        } catch (SQLException e) {
            String mensajeError = "Error al cargar los productos más vendidos: " + e.getMessage();
            mostrarMensajeError(mensajeError);
        }
    }

    private void colocarProductosEnTabla() {

        String[] columnas = {
                "Código Producto",
                "Nombre Producto",
                "Cantidad Vendida"
        };

        DefaultTableModel modeloInsumos = crearModelo(columnas);

        if (productosMasVendidos != null) {
            for (ProductoMasVendido producto : productosMasVendidos) {
                modeloInsumos.addRow(convertirProductoAFila(producto));
            }
        }

        jTableProductos.setModel(modeloInsumos);
    }

    private DefaultTableModel crearModelo(String[] columnas) {
        return new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
    }

    private Object[] convertirProductoAFila(ProductoMasVendido producto) {
        return new Object[] {
                producto.getCodigoProducto(),
                producto.getNombreProducto(),
                producto.getCantidadVendida()
        };
    }

    private void mostrarMensajeError(String mensaje) {
        MensajeDialogFrame mensajeDialogFrame = new MensajeDialogFrame(null, true, mensaje, true);
        mensajeDialogFrame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jPanelTitulo = new javax.swing.JPanel();
        jLabelTituloLista = new javax.swing.JLabel();
        jPanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonExportarHTML = new javax.swing.JButton();

        jPanel.setBackground(new java.awt.Color(50, 52, 35));
        jPanel.setLayout(new java.awt.BorderLayout());

        jPanelTitulo.setBackground(new java.awt.Color(50, 52, 35));

        jLabelTituloLista.setBackground(new java.awt.Color(50, 52, 35));
        jLabelTituloLista.setFont(new java.awt.Font("Noto Sans CJK JP Black", 1, 15)); // NOI18N
        jLabelTituloLista.setForeground(new java.awt.Color(227, 135, 88));
        jLabelTituloLista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloLista.setText("Productos Mas Vendidos");
        jLabelTituloLista.setOpaque(true);
        jPanelTitulo.add(jLabelTituloLista);

        jPanel.add(jPanelTitulo, java.awt.BorderLayout.NORTH);

        jPanelTabla.setBackground(new java.awt.Color(50, 52, 35));
        jPanelTabla.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 20, 20, 20));
        jPanelTabla.setLayout(new java.awt.BorderLayout());

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(jTableProductos);

        jPanelTabla.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel.add(jPanelTabla, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(50, 52, 35));

        jButtonExportarHTML.setBackground(new java.awt.Color(227, 135, 88));
        jButtonExportarHTML.setFont(new java.awt.Font("Noto Sans CJK JP Black", 0, 12)); // NOI18N
        jButtonExportarHTML.setText("Exporta HTML");
        jButtonExportarHTML.addActionListener(this::jButtonExportarHTMLActionPerformed);
        jPanel2.add(jButtonExportarHTML);

        jPanel.add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExportarHTMLActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonExportarHTMLActionPerformed
        seleccionarRutaArchivoYGuardar();
    }// GEN-LAST:event_jButtonExportarHTMLActionPerformed

    private void seleccionarRutaArchivoYGuardar() {
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setDialogTitle("Guardar archivo HTML");
        fileChooser.setSelectedFile(new java.io.File("productos_mas_vendidos.html"));

        int resultado = fileChooser.showSaveDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            if (!archivo.getName().toLowerCase().endsWith(".html")) {
                archivo = new File(archivo.getAbsolutePath() + ".html");
            }

            try {
                ExportadorProctoTopHTML exportador = new ExportadorProctoTopHTML();
                exportador.exportar(archivo);
                String mensajeExito = "Productos más vendidos exportados exitosamente";
                MensajeDialogFrame mensajeDialog = new MensajeDialogFrame(null, true, mensajeExito, false);
                mensajeDialog.setVisible(true);
            } catch (IOException e) {
                String mensajeError = "Error al exportar los productos más vendidos: " + e.getMessage();
                mostrarMensajeError(mensajeError);
            } catch (SQLException e) {
                String mensajeError = "Error al exportar los productos más vendidos: " + e.getMessage();
                mostrarMensajeError(mensajeError);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExportarHTML;
    private javax.swing.JLabel jLabelTituloLista;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JPanel jPanelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    // End of variables declaration//GEN-END:variables
}
